spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pos?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

