server:
  port: 9000
eureka:
  client:
    # this.serviceUrl.put(DEFAULT_ZONE, DEFAULT_URL);
    service-url:
      # DEFAULT_URL = "http://localhost:8761" + DEFAULT_PREFIX
      defaultZone: http://localhost:9001/eureka/

logging:
  level:
    org.springframework.cloud: debug