nacos:
  discovery:
    server-addr: 127.0.0.1:8848
    username: nacos
    password: nacos
  config:
    server-addr: 127.0.0.1:8848
    username: nacos
    password: nacos

server:
  port: 8787

spring:
  application:
    name: learn-spring-boot-nacos
