server:
  port: 8976

spring:
  kafka:
    consumer:
      bootstrap-servers: 172.26.1.22:9094
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

rocketmq:
  name-server: localhost:9876
