spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          #enables DiscoveryClient gateway integration
          enabled: true
          #lower case serviceId in predicates and filters, defaults to false
          lowerCaseServiceId: true
server:
  port: 8999
eureka:
  client:
    # this.serviceUrl.put(DEFAULT_ZONE, DEFAULT_URL);
    service-url:
      # DEFAULT_URL = "http://localhost:8761" + DEFAULT_PREFIX
      defaultZone: http://localhost:9001/eureka/

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: debug

