server:
  port: 8081

sa-token:
  token-name: satoken
  #token??????(??:?) ??30?, -1????
  timeout: 2592000
  #token?????
  activity-timeout: -1
  #????????????
  is-concurrent: true
  #?????????????????token
  is-share: false
  #token??(??????uuid?simple-uuid?random-32?random-64?random-128?tik)
  token-style: uuid
  #????????
  is-log: false

spring:
  redis:
    database: 1
    host: *
    port: 6379
    password:
    timeout: 15s
    connect-timeout: 10s
    lettuce:
      pool:
        max-active: 30
        max-wait: -1
        max-idle: 10
        min-idle: 0
