version: '3'
services:
  namesrv:
    image: apache/rocketmq:latest
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    command: sh mqnamesrv
  broker:
    image: apache/rocketmq:latest
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - /Users/twx/code-space/docker/rocketmq/broker.conf:/home/rocketmq/rocketmq-5.1.4/conf/broker.conf
      - /Users/twx/code-space/docker/rocketmq/acl.yaml:/home/rocketmq/rocketmq-5.1.4/conf/plain_acl.yml
    command: sh mqbroker -n namesrv:9876 -c ../conf/broker.conf
    depends_on:
      - namesrv
  # console:
  #   image: styletang/rocketmq-console-ng
  #   container_name: rocketmq-console-ng
  #   ports:
  #     - 8181:8080
  #   depends_on:
  #     - namesrv
  #   environment:
  #     - JAVA_OPTS= -Dlogging.level.root=info -Drocketmq.namesrv.addr=rmqnamesrv:9876
  #     - Dcom.rocketmq.sendMessageWithVIPChannel=false
