server:
  port: 9000
  servlet:
    context-path: /

spring:
  application:
    name: skeleton
  profiles:
    active: dev
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/,classpath:/static/, classpath:/public/,file:${soyuan.thumbnailDir}
#    不需要sentinel的话也可以不配
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
#  配置redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      shutdown-timeout: 200ms
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms
