server:
  port: 9000
  servlet:
    context-path: /

spring:
  application:
    name: skeleton
  profiles:
    active: dev
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/,classpath:/static/, classpath:/public/,file:${soyuan.thumbnailDir}
#    不需要sentinel的话也可以不配
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8858
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            data-id: learn-sentinel
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow
      eager: true
  #  配置redis
  redis:
    host: 47.96.98.119
    port: 6379
    password: ******
    database: 0
    lettuce:
      shutdown-timeout: 200ms
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms

